name: uts_garong_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.2
  image_picker: ^1.1.2
  provider: ^6.1.4
  intl: ^0.20.2
  firebase_database: ^11.3.5
  cached_network_image: ^3.4.1
  logging: ^1.3.0
  midpay: ^1.1.7
  http: ^1.3.0
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/google.png
