name: uts_garong_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.2
  image_picker: ^1.1.2
  provider: ^6.1.4
  intl: ^0.20.2
  firebase_database: ^11.3.5
  cached_network_image: ^3.4.1
  logging: ^1.3.0
  midpay: ^1.1.7
  http: ^1.3.0
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^13.0.4
  flutter_map_location_marker: ^10.0.0
  flutter_launcher_icons: ^0.14.3
  tutorial_coach_mark: ^1.2.13
  logger: ^2.5.0
  google_sign_in: ^6.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  launcher_name: ^1.0.2
  

launcher_name:
  default: "Garong"
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"  
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/google.png
    - assets/images/village.jpg
    - assets/images/sapi.jpg
    - assets/images/laundry.jpg
    - assets/images/logo.png
    - assets/images/Sania.jpg
    - assets/images/gulaku.jpg
    - assets/images/sembako.jpg
    - assets/images/grocery.png
    - assets/images/drink.png
    - assets/images/snack.png
    - assets/images/salt.png
    - assets/images/Hec.jpg
    - assets/images/air.jpg
    - assets/images/teh.jpg
    - assets/images/keripik.jpg
    - assets/images/coklat.jpg
    - assets/images/garam.jpg
    - assets/images/minyak.jpg
    - assets/images/qris.png
    - assets/images/shopeepay.png
    - assets/images/gopay.png
    - assets/images/transfer.png
    - assets/images/qris_logo.png
    - assets/images/bca_logo.png
    - assets/images/bni_logo.png
    - assets/images/mandiri_logo.png
    - assets/images/sembako.jpg
    - assets/images/map_background.jpg
    - assets/images/gratong.png
    - assets/images/diskon.png

